### ISSUE TITLE
modules get prioritised over their members starting from 3.11

### ISSUE THREAD

**Issue by LightArrowsEXE** [OpusGang/rekt#1]
(Moved from GitLab)

As of 3.11, modules *always* get prioritised over members.

```py
2023-02-12 12:38:41.625: root: ERROR: Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\vsengine\vpy.py", line 219, in _execute
    runpy.run_path(str(script), module.__dict__, module.__name__)
  File "C:\Program Files\Python311\Lib\runpy.py", line 291, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\runpy.py", line 98, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\Python311\Lib\site-packages\vspreview\core\vsenv.py", line 19, in _monkey_runpy_func
    glob_dict = orig_runpy_run_code(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\Illyasviel\Desktop\Projects\Joshiraku\JoshirakuBD_14.py", line 66, in <module>
    FILTERED = filterchain(SRC.clip_cut, NCOP.clip_cut, NCED.clip_cut, OP_03.clip_cut)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Illyasviel\Desktop\Projects\Joshiraku\JoshirakuBD_14.py", line 37, in filterchain
    return chain.filterchain(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Illyasviel\Desktop\Projects\Joshiraku\project_module\chain.py", line 75, in filterchain
    rkt = rektlvls(clip, [0, -1], [17, 16], [0, 1, 2, 3, -3, -2, -1], [16, 4, -2, 2, -2, 5, 14])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rekt\rektlvls.py", line 87, in rektlvls
    clip = _rektlvl(clip, rownum[_], rowval[_], alignment='row', prot_val=prot_val, min_val=min_val, max_val=max_val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rekt\rektlvls.py", line 52, in _rektlvl
    last = rekt_fast(c, last, bottom=c.height - num - 1, top=num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```

I also suggest making these *relative imports* to avoid any potential future collisions.

**Comment by quietvoid** [comment]
I can't seem to be able to reproduce the issue with this sample script:

```python
import vapoursynth as vs
from vapoursynth import core

from rekt import rektlvls

clip = core.std.BlankClip(width=1920, height=1080, format=vs.YUV420P8)
clip = rektlvls(clip, [0, -1], [17, 16], [0, 1, 2, 3, -3, -2, -1], [16, 4, -2, 2, -2, 5, 14])

clip.get_frame(0)
```

Running Python 3.11.2, with `vs-rekt` 1.0.0 from pypi.

**Comment by LightArrowsEXE** [comment]
Happens to me, even with the same code.

```py
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth as vs
>>> core = vs.core
>>> from rekt import rektlvls
>>> clip = core.std.BlankClip(width=1920, height=1080, format=vs.YUV420P8)
>>> clip = rektlvls(clip, [0, -1], [17, 16], [0, 1, 2, 3, -3, -2, -1], [16, 4, -2, 2, -2, 5, 14])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

```py
>>> type(rektlvls)
<class 'module'>
```

However, it does work if I use `from rekt.rektlvls import rektlvls`

```py
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rekt.rektlvls import rektlvls
>>> type(rektlvls)
<class 'function'>
>>> import vapoursynth as vs
>>> core = vs.core
>>> clip = core.std.BlankClip(width=1920, height=1080, format=vs.YUV420P8)
>>> clip = rektlvls(clip, [0, -1], [17, 16], [0, 1, 2, 3, -3, -2, -1], [16, 4, -2, 2, -2, 5, 14])
>>> clip.get_frame(0)
<vapoursynth.VideoFrame object at 0x000001FBB9A7D070 format=YUV420P8, width=1920, height=1080, readonly=True>
```

My proposed suggestion should fix this and make it work for both.

**Comment by quietvoid** [comment]
Right, well I'm just trying to verify if the fixes from https://github.com/OpusGang/rekt/commits/fixes work.
If you can try either that branch or https://github.com/OpusGang/rekt/pull/2 and let me know.

**Comment by LightArrowsEXE** [comment]
Small correction to my third code block, I had fixed it locally by changing it to a relative import already.

```py
from .rekt_fast import rekt_fast
```

Reverting this change introduces the error again.



> Right, well I'm just trying to verify if the fixes from https://github.com/OpusGang/rekt/commits/fixes work. If you can try either that branch or #2 and let me know.

Will do 👍

**Comment by LightArrowsEXE** [comment]
Swapping branches, it now properly returns a function instead of a module.

```py
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rekt import rektlvls
>>> type(rektlvls)
<class 'function'>
>>>
```

**Comment by quietvoid** [comment]
Cool. Thanks.
